### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by jgehry82** [liuziangexit/HEIF-Utility-CommandLineTool#1]
cmake成xcode工程，编译无法通过，兄弟，能否提供命令行工具 for mac。

**Comment by liuziangexit** [comment]
我也想帮你啊。。可是我没有 Mac 电脑

**Comment by liuziangexit** [comment]
Mac 的话你可以下一个 iMazing 的 HEIC 转换器。。。尽管那玩意儿在转换质量和转换速度上都比我的落后一大截，但是至少能用。。。

**Comment by jgehry82** [comment]
编译链接通过了，也加入了libopencv_world.3.3.0.dylib，但遇到一个问题了，调用cv::VideoCapture vcap(filename)方法时，出现了“OpenCV: Couldn't read video stream from file "temp_bitstream.hevc“”，也尝试过MP4、jpeg文件，有些文件能正确打开。不知道是哪里出问题了，能否帮我看一下。

**Comment by liuziangexit** [comment]
加我微信 liuzianglunars，然后你开个 teamviewer，我远程看一下

**Comment by jgehry82** [comment]
OK

**Comment by plokijuhhb** [comment]
你好 请问这个问题解决了么   感觉这个问题应该是缺少hevc的解码器所致

**Comment by liuziangexit** [comment]
@plokijuhhb 没有解决。确实是由于opencv没有hevc解码器导致的，在 Windows 上可以自己编译，但是 macOS 我就不知道怎么弄了

**Comment by plokijuhhb** [comment]
好的  多谢
