### ISSUE TITLE
大神，能提供一个jpg转heif 在线的，要求实时处理的这种思路吗？

### ISSUE THREAD

**Issue by ghost** [liuziangexit/HEIF-Utility-CommandLineTool#4]
大神，能提供一个jpg转heif 在线的，要求实时处理的这种思路吗？

**Comment by liuziangexit** [comment]
已经做了一个:
https://liuziangexit.com/HEIF-Utility/Online/
用 ASP.NET 做的，源代码在 https://github.com/liuziangexit/HEIF-Utility-Online ，不过这些代码仅供参考，需要一些特定的修改才能运行。
