### ISSUE TITLE
求助 liuziangexit/heif   example.cpp 程序运行出错

### ISSUE THREAD

**Issue by jernen** [liuziangexit/HEIF-Utility-CommandLineTool#5]
有个问题想请教一下你， 我在github 上下了您的代码主题：  liuziangexit/heif， 地址：https://github.com/liuziangexit/heif.git
我编译了： heif/Srcs/examples/example.cpp    这个文件后，测试一张iphone7所拍摄的heic图片后, 源代码如下：  

#include "../../Srcs/reader/hevcimagefilereader.hpp"
#include <iostream>
using namespace std;

void example1()
{
    HevcImageFileReader reader;
    reader.initialize("test_001.heic");
    const auto& properties = reader.getFileProperties();

    // Verify that the file has a cover image
    if (not properties.fileFeature.hasFeature(ImageFileReaderInterface::FileFeature::HasCoverImage))
    {
        return; // Nothing to do, just return.
    }

    // The cover image is always located in the root level MetaBox, so get MetaBox context ID.
    const uint32_t contextId = properties.rootLevelMetaBoxProperties.contextId;

    // Find the item ID
    const uint32_t itemId = reader.getCoverImageItemId(contextId);

    ImageFileReaderInterface::DataVector data;
    reader.getItemDataWithDecoderParameters(contextId, itemId, data);

    // Feed 'data' to decoder and display the cover image...
}

int main()
{
    example1();

}

编译并运行后，出现以下错误，运行系统为 Linux debian 3.16.0-4-amd64：

zsw@debian:~/tmp/heif/Srcs/examples$ ./example
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
terminate called after throwing an instance of 'std::out_of_range'**
  what():  map::at
已放弃
zsw@debian:~/tmp/heif/Srcs/examples$ 

请帮忙分析下原因，谢谢！

**Comment by jernen** [comment]
错误信息如下：不知道上面的留言为什么会自动划掉了。
zsw@debian:~/tmp/heif/Srcs/examples$ ./example
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
Skipping an unknown box of type 'colr' in ItemPropertyContainer.
Skipping an unknown box of type 'pixi' in ItemPropertyContainer.
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
已放弃

**Comment by liuziangexit** [comment]
std::out_of_range 是读取 std::map 越界抛的异常。加断点会吧？你加几个断点看看在哪死的就知道了。

**Comment by jernen** [comment]
哦，大神之前没有遇到同类的问题? 主要的是对此程序不熟，不太明白这个最简单的测试程序为什么都用不了， 不知道是否与编译平台有关系。

**Comment by liuziangexit** [comment]
@jernen 你编译原版的HEIF试试：https://github.com/nokiatech/heif

**Comment by jernen** [comment]
原版本的也是一样的问题，已试过了。

**Comment by jieweijasson** [comment]
兄弟，怎么运行examples

**Comment by jassonjackson** [comment]
碰到了同样的问题，请问怎么解决？

**Comment by liuziangexit** [comment]
@jieweijasson 
诺基亚的原始版本也有这个问题，这个不是我的锅，你应该去问诺基亚
![image](https://user-images.githubusercontent.com/15322450/36823689-51d42a92-1d39-11e8-8482-917ad39f4acd.png)

**Comment by jassonjackson** [comment]
那有什么办法可以解决该问题吗？

**Comment by liuziangexit** [comment]
我不知道..

**Comment by jassonjackson** [comment]
好吧，谢谢🙏
