### ISSUE TITLE
在centos7下cmake，make之后，出现了这些问题，请问哪里需要修改，谢谢

### ISSUE THREAD

**Issue by jassonjackson** [liuziangexit/HEIF-Utility-CommandLineTool#7]
<img width="616" alt="default" src="https://user-images.githubusercontent.com/35954603/35609525-9d08ca0c-0698-11e8-8357-47ee8a3908b7.png">

**Comment by liuziangexit** [comment]
您好，关于这个编译错误，以下链接给出了简单的解决方法
https://github.com/liuziangexit/heif/blob/master/README.md
按照该链接所说的去做，就可以通过编译。
但是这个程序在Linux上运行将会遇到一些问题，因为opencv默认版本的动态库不支持hevc解码，所以运行时将会在read_hevc_bitstream_to_mat_vector函数处出现运行时错误。
解决方法是，您需要自己打开opencv的cmake的“hevc支持”的编译选项，然后重新编译一遍opencv，那是一个复杂的工程。
在您完成编译了支持hevc的opencv后，将opencv的库文件复制到本项目的目录，应该就能运行成功。

**Comment by jassonjackson** [comment]
非常感谢子昂为我解决无法编译的问题，非常的感谢！！！




------------------ 原始邮件 ------------------
发件人: "liuziangexit";<notifications@github.com>;
发送时间: 2018年1月31日(星期三) 下午3:19
收件人: "liuziangexit/HEIF-Utility-Native-DLL"<HEIF-Utility-Native-DLL@noreply.github.com>;
抄送: "揭伟"<1147155464@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [liuziangexit/HEIF-Utility-Native-DLL] 在centos7下cmake，make之后，出现了这些问题，请问哪里需要修改，谢谢 (#7)




您好，关于这个编译错误，以下链接给出了简单的解决方法
 https://github.com/liuziangexit/heif/blob/master/README.md
 按照该链接所说的去做，就可以通过编译。
 但是这个程序在Linux上运行将会遇到一些问题，因为opencv默认版本的动态库不支持hevc解码，所以运行时将会在read_hevc_bitstream_to_mat_vector函数处出现运行时错误。
 解决方法是，您需要自己打开opencv的cmake的“hevc支持”的编译选项，然后重新编译一遍opencv，那是一个复杂的工程。
 在您完成编译了支持hevc的opencv后，将opencv的库文件复制到本项目的目录，应该就能运行成功。

**Comment by jassonjackson** [comment]
还是一样的错误，为啥？是我没改对吗
<img width="583" alt="qq20180131-0" src="https://user-images.githubusercontent.com/35954603/35624272-7f06fb7e-06c9-11e8-86dc-8a3d23550b91.png">

**Comment by liuziangexit** [comment]
![default](https://user-images.githubusercontent.com/15322450/35630872-67d2558e-06dd-11e8-9b68-034ccfd57b92.jpeg)
您好，我想大概是您没改对。首先您要知道，在Unix上的大部分配置文件里，“#”意味着注释掉这一行，这说明您的修改完全没有起到任何作用。

请尝试像上图中这样进行修改，然后cmake CMakeLists.txt，然后make。
因为有几个月了，所以我不太记得需要怎么修改了。因为现在很晚了，请您暂且按照上图的方式试一下，如果不行的话，我明天晚上去我的centos试一试，然后给您确切答复。

**Comment by jassonjackson** [comment]
子昂，按您上述的方法改，还是一样的问题，但是我修改成下图之后，这个错误解决了，但是出现了如下错误，我想这就是您说的opencv默认版本的动态库不支持hevc解码这个问题。
<img width="1222" alt="2018-02-01 10 12 58" src="https://user-images.githubusercontent.com/35954603/35657789-476f3ea4-0739-11e8-85b8-35b33363ddc0.png">

**Comment by liuziangexit** [comment]
不是不是，您这个是编译错误，是没有opencv的头文件，您需要把opencv头文件添加到编译器include目录。

我说的那个不支持hevc解码的问题是运行时错误，不是编译错误。。。我觉得您还是放弃在Linux上运行这玩意儿的打算吧，确实特别麻烦。Windows上的编译运行会稍微简单一些。。。
